### PR TITLE
fix(outlook): fixed filter error in outlook sub plugin

### LINKED ISSUE #15: [Plugin io.kestra.plugin.microsoft365.outlook.List] Error produced filter is applied.
### Describe the issue

Given the following task:

```
  - id: get_one
    type: io.kestra.plugin.microsoft365.outlook.List
    tenantId: "{{ kv('AZURE_TENANT_ID') }}"
    clientId: "{{ kv('AZURE_CLIENT_ID') }}"
    clientSecret: "{{ kv('AZURE_CLIENT_SECRET') }}"
    userEmail: "user@example.com"
    folderId: "inbox"
    filter: "subject eq 'my subject'"
    fetchType: FETCH_ONE
    top: 1
```

The following error is produced:

`com.microsoft.graph.models.odataerrors.ODataError: The restriction or sort order is too complex for this operation.`

I started a Slack thread [here](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1763310775471509). I believe that the lack of "Order By" may be causing this issue according to this MS [article](https://learn.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http#optional-query-parameters).

Ultimately I'd like a filter like this to work:

`filter: "subject eq 'my subject' and hasAttachments eq true"`

Also according to the thread above commenting out line 63 could solve the issue.
https://kestra-io.slack.com/files/U07B8QWQTEF/F09UDGSQ2QH/e17fb801-08dc-4bae-9ea7-c136d6f82faf.jpg

### Environment

- Kestra Version: develop 1.1.4

### PR DESCRIPTION
**Pull request by bishalbera**
closes #15

### CODE REVIEW

**Comment by bishalbera** [comment]
@fdelbrayelle Please have a look at this when you've time

File: src/main/java/io/kestra/plugin/microsoft365/outlook/utils/GraphMailUtils.java [hunk 1]
```diff
@@ -84,8 +91,15 @@ public static List<Message> fetchMessagesForTrigger(
                 throw new IllegalStateException("Query parameters are null");
             }
 
-            if (filterExpression != null) {
-                requestConfig.queryParameters.filter = filterExpression;
+            // To use $orderby with $filter, the orderby property must appear in the filter first
+            String finalFilter = filterExpression;
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/microsoft365/outlook/utils/GraphMailUtils.java:95]: Hmm not sure to understand why this duplicated code is repeated here?

Comment (bishalbera) [reply src/main/java/io/kestra/plugin/microsoft365/outlook/utils/GraphMailUtils.java:95]: This one is for the trigger @fdelbrayelle

Comment (fdelbrayelle) [reply src/main/java/io/kestra/plugin/microsoft365/outlook/utils/GraphMailUtils.java:95]: ah sorry yes !

**Comment by fdelbrayelle** [comment]
@bishalbera Could you take the initial issue case and send QA screenshots showing it's now OK without any error :pray: ?

**Comment by bishalbera** [comment]
> @bishalbera Could you take the initial issue case and send QA screenshots showing it's now OK without any error 🙏 ?

```yaml
id: deer_508484
namespace: company.team

tasks:
    - id: get_one
      type: io.kestra.plugin.microsoft365.outlook.List
      tenantId: ""
      clientId: ""
      clientSecret: ""
      userEmail: ""
      folderId: "inbox"
      filter: "subject eq 'Test'"
      fetchType: FETCH_ONE
      top: 1

id: deer_508484
namespace: company.team

tasks:
    - id: get_one
      type: io.kestra.plugin.microsoft365.outlook.List
      tenantId: ""
      clientId: "1"
      clientSecret: ""
      userEmail: ""
      folderId: "inbox"
      filter: "subject eq 'Test' and hasAttachments eq true"
      fetchType: FETCH_ONE
      top: 1
```
      
image
image

File: src/main/java/io/kestra/plugin/microsoft365/outlook/utils/GraphMailUtils.java [hunk 2]
```diff
@@ -84,8 +91,15 @@ public static List<Message> fetchMessagesForTrigger(
...
+            if (filterExpression != null && !filterExpression.isEmpty()) {
+                // Prepend receivedDateTime condition to satisfy Graph API requirements
+                finalFilter = "receivedDateTime ge 1970-01-01T00:00:00Z and (" + filterExpression + ")";
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/microsoft365/outlook/utils/GraphMailUtils.java:98]: Hmm why specifically this date here @bishalbera ?
It's the "timestamp 0" but then?

**Review by fdelbrayelle — APPROVED** [review]

File: src/main/java/io/kestra/plugin/microsoft365/outlook/utils/GraphMailUtils.java (hunk 2 above)
Comment (bishalbera) [reply src/main/java/io/kestra/plugin/microsoft365/outlook/utils/GraphMailUtils.java:98]: Yes, 1970-01-01T00:00:00Z is the Unix epoch. The Microsoft Graph API requires a 
  `receivedDateTime` condition in filter expressions for certain queries. Since no 
  emails could have been received before 1970 (predates email and Microsoft services),
   using `receivedDateTime ge 1970-01-01T00:00:00Z` effectively means "all emails"
  without filtering anything out. This satisfies the API requirement while preserving
  all user-specified filters in the filterExpression. I was using some old dates but claude suggested me this then 😅 @fdelbrayelle
